[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Швидкість прошивки та монітора порту під ваші налаштування
upload_speed = 921600
monitor_speed = 9600
; Підставте свій реальний COM-порт, наприклад COM4. Якщо не знаєте, подивіться в диспетчері пристроїв.
upload_port = COM4
monitor_port = COM4

; Менеджер залежностей з прямим посиланням на GitHub SolarPosition
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    PaulStoffregen/Time @ ^1.6.1
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    https://github.com/KenWillmott/SolarPosition.git

; OTA через Wi-Fi (після того, як ESP вже буде підключений до мережі)
; 1. Підставте IP ESP, яке він показав у Serial Monitor або на OLED
; 2. Не змінюйте пароль, якщо він збігається з тим, що в коді (esp8266)
;upload_protocol = espota
;upload_port = 192.168.1.216 ; !!! ВАЖЛИВО: ЗАМІНІТЬ НА РЕАЛЬНИЙ IP ПРИСТРОЮ !!!
;upload_flags = --auth=esp8266
